parameters:
    transaction.factory.class:   Theodo\DrinksBundle\Factory\TransactionFactory
    stock.factory.class:         Theodo\DrinksBundle\Factory\StockFactory
    drinks.user_provider.class:  Theodo\DrinksBundle\Security\User\UserProvider

    drinks.converter.doctrine.odm.mongodb.class: Theodo\DrinksBundle\Request\ParamConverter\MongodbParamConverter

services:
    transaction.factory:
        class: %transaction.factory.class%
        arguments:
            - @translator
    stock.factory:
        class: %stock.factory.class%
        arguments:
            - @doctrine.odm.mongodb.document_manager

    drinks.user_provider:
        class: %drinks.user_provider.class%
        arguments:
            - @doctrine.odm.mongodb.document_manager

    drinks.converter.doctrine.odm.mongodb:
        class: %drinks.converter.doctrine.odm.mongodb.class%
        tags:
            - { name: request.param_converter, converter:doctrine.odm }
        arguments:
            - @doctrine_mongodb
